# Generated by Django 2.1.7 on 2019-03-10 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel_Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='plan_id')),
                ('country', models.CharField(max_length=128, verbose_name='Country')),
                ('state', models.CharField(max_length=128, verbose_name='State')),
                ('city', models.CharField(max_length=128, verbose_name='City')),
                ('budget', models.IntegerField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'travel_Plan',
            },
        ),
    ]
