# Generated by Django 2.1.7 on 2019-03-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190311_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_plan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='users.UserProfile'),
        ),
    ]
