# Generated by Django 2.1.7 on 2019-03-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190320_2335'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travel_plan',
            unique_together={('country', 'state', 'city', 'start_time', 'end_time')},
        ),
    ]
