# Generated by Django 2.1.7 on 2019-03-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190322_2023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travel_plan',
            unique_together={('country', 'state', 'city', 'start_time', 'end_time', 'user')},
        ),
    ]
