# Generated by Django 2.1.7 on 2019-04-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190324_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.travel_Plan')),
                ('plan_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_list_requests_created', to='users.travel_Plan')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_list_requests_created', to='users.UserProfile')),
            ],
            options={
                'verbose_name': 'Match_List',
                'abstract': False,
            },
        ),
    ]
