# Generated by Django 2.1.7 on 2019-04-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_match_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_list',
            name='status',
            field=models.CharField(default='matched', max_length=3),
        ),
    ]
