# Generated by Django 2.1.7 on 2019-04-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_match_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_list',
            name='status',
            field=models.CharField(default=True, max_length=10, verbose_name='matched'),
        ),
    ]
