# Generated by Django 2.1.7 on 2019-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190413_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_list',
            name='status',
            field=models.CharField(default='matched', max_length=10, verbose_name='status'),
        ),
    ]
