# Generated by Django 2.1.7 on 2019-04-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190413_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_plan',
            name='status',
            field=models.CharField(default='unmatched', max_length=10),
        ),
    ]
